---
name: Backport merged pull request

on:
  workflow_call:
    secrets:
      ssh_private_key:
        description: 'ssh private key to sign commits'
        required: true
      github_pat:
        # Provide a fine-grained token with the following repository permissions:
        # * Contents: Read and write
        # * Metadata: Read-only (mandatory, default)
        # * Pull requests: Read and write
        description: 'PAT to access the GitHub API'
        required: true

permissions: {}

jobs:
  backport:
    name: Backport merged pull request
    runs-on: ubuntu-26.04
    # For security reasons, we don't want to checkout and run arbitrary code when
    # using the pull_request_target trigger. So restrict this to cases where the
    # backport label is applied to an already merged PR.
    if: github.event.pull_request.merged && startsWith(github.event.label.name, 'backport ')
    steps:
      - name: Setup git and SSH signing
        id: git_identity
        uses: $/.github/actions/setup-git-ssh-signing
        with:
          ssh_private_key: ${{ secrets.ssh_private_key }}
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.github_pat }}
          ref: main
      - name: Create backport pull requests
        uses: korthout/backport-action@2e830a1d0b8269505846ddd407a70876913ad1f8 # v4.6.0
        with:
          auto_merge_enabled: true
          auto_merge_method: merge
          github_token: ${{ secrets.github_pat }}
          git_committer_name: ${{ steps.git_identity.outputs.git_committer_name }}
          git_committer_email: ${{ steps.git_identity.outputs.git_committer_email }}
