name: Sync any source updates
on:
  workflow_call:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Back up and sync all updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ github.event.repository.name }}
      run:  |
        MIRROR_DATE=$(date --date=$(gh repo view overlookinfra/${REPO_NAME} --json 'updatedAt' -t '{{ .updatedAt }}') '+%s')
        UPSTREAM_DATE=$(date --date=$(gh repo view puppetlabs/${REPO_NAME} --json 'updatedAt' -t '{{ .updatedAt }}') '+%s')

        echo "MIRROR_DATE: ${MIRROR_DATE}"
        echo "UPSTREAM_DATE: ${UPSTREAM_DATE}"

        # Only mirror if there are actually updates
        if [[ $MIRROR_DATE -ge $UPSTREAM_DATE ]]; then exit 0; fi
        
        git remote add upstream $(git config --get remote.origin.url | sed 's|overlookinfra|puppetlabs|')
        git fetch -p upstream

        TODAY=$(date -I)
        for BRANCH in $(git --no-pager branch -r --format='%(refname:short)' --list 'upstream*')
        do
          NAME=$(echo $BRANCH | sed 's|upstream/||')

          git branch "backup/$TODAY/$NAME" $BRANCH
          git push origin "backup/$TODAY/$NAME"

          git fetch upstream +refs/heads/$NAME:$NAME
          git push origin $NAME
        done

        git push origin --tags
